[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LSODA = "7f56f5a3-f504-529b-bc02-0b1fe5e64312"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Measurements = "eff96d63-e80a-5855-80a2-b1b0885c5ab7"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
ProjectRoot = "e3f974f6-674d-4b8e-a3d1-5850677db852"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Sundials = "c3572dad-4567-51f8-b174-8c6c989267f4"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
TerminalLoggers = "5d786b92-1e48-4d6f-9151-6b4477ca9bed"
Tidier = "f0413319-3358-4bb0-8e7c-0c83523a93bd"
